apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hana-service-key
  namespace: <namespace>
## remember base64
data:
  client_id: 
  client_secret: 
  instance_name: 
  service_manager_url: 
  token_url: 

