apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hana-service-key
  namespace: <namespace>
data:
  client_id: base64-encoded-string
  client_secret: base64-encoded-string
  instance_name: base64-encoded-string
  service_manager_url: base64-encoded-string
  token_url: base64-encoded-string

